version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - '27017:27017'
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=maxmilhas

networks:
  app-network:
    driver: bridge